### ISSUE TITLE
BRITS implementation

### ISSUE THREAD

**Issue by pbansal5** [eXascaleInfolab/bench-vldb20#1]
Hi,

The README file for the repo says that the codebase supports BRITS implementation, though I was unable to locate the files for the same. Also in the arguments section, --alg doesn't seem to support brits flag. Clarity on this would be appreciated

Parikshit

**Comment by mkhayati** [comment]
We had some problems integrating BRITS into the benchmark using some scenarios. We hope that this algorithm will be fully integrated by the end of next week.

**Comment by pbansal5** [comment]
Hi Mourad,

Any updates on BRITS?? The reason for the same being that we plan to use this benchmark for our experimentation and BRITS would be a necessary part for the same. Thanks for your time. 

Parikshit

**Comment by mkhayati** [comment]
Hello Parikshit,

Thanks for your request. We have finally integrated BRITS into our benchmark. Some (important) comments:
- Please fork the new version of the repo
- Please make sure that you install the extra dependencies using: _sh install_extra.sh_
- Please run the algorithm with the name "brits". For example to execute brits on chlorine dataset with the missing percentage scenario, execute: _mono TestingFramework.exe -alg brits -d chlorine -scen miss_perc_ 
- To update the number of epochs (for example to 50), please use _-algx brits 50_ instead of _-alg brits_
- BRITS recovers only one incomplete series at the time. The only applicable scenarios are: miss_perc, ts_length and ts_nbr
- Please keep in mind that BRITS takes a lot of time to run.

Best regards,
Mourad.
