### ISSUE TITLE
Error on Running MRNN

### ISSUE THREAD

**Issue by pbansal5** [eXascaleInfolab/bench-vldb20#2]
Hi,

I tried to run MRNN algorithm with AIRQ dataset in MCAR setting but I got the following error : 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "testerMRNN.py", line 14, in mrnn_recov
    _, Recover_testX = M_RNN(trainZ, trainM, trainT, testZ, testM, testT)
  File "M_RNN.py", line 20, in M_RNN
    seq_length = len(trainZ[0,:,0])
IndexError: too many indices for array

How can I resolve this issue?

**Comment by mkhayati** [comment]
Hello,
You are getting this error because MRNN expects the first row(s) of the input matrix to be complete, which is not guaranteed by the mcar scenario.  This algorithmic problem is not easy to fix! We have decided to exclude MRNN from all multi-col tests! In case you are interested in the evaluation of mrnn for muli-col scenarios, you can check our other streaming benchmark: https://github.com/eXascaleInfolab/orbits

**Comment by pbansal5** [comment]
Sure,
Thanks for the clarification
